project_id = "dzohlljggpxmitgwzcwc"

[functions.create-employee-login]
verify_jwt = false

[functions.handle-email-action]
verify_jwt = false

[functions.process-yearly-rollover]
verify_jwt = false

[functions.reset-employee-password]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.generate-payslips]
verify_jwt = false

[functions.preview-payslip-template]
verify_jwt = false
